name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  parse-bag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install dependencies
      working-directory: scripts
      run: |
        npm ci

    - name: Run Script
      working-directory: scripts
      run: |
        npm start
        
    - name: Set commit message
      continue-on-error: true
      run: |
        echo ::set-env name=commit_msg::Update BAG-Data (${date})
        
    - name: Check if there are changes in the repo
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
        
    - name: Commit and push to repo
      if: steps.changes.outputs.changed == 1 # only try to commit if there are actually changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Scraper
        email: scraper@salzer.it
        commit-message: ${{ env.commit_msg }}
        rebase: 'true'
